=== alex-kukhtin/A2v10.App.Designer/A2v10.Application/App_application/@schemas/model-json-schema.json
{
	"$schema": "http://json-schema.org/draft-04/schema",
	"$version": "10.0.7696",
	"title": "JSON Schema for model.json",
	"type": "object",

	"properties": {
		"$schema": { "type": "string" },
		"source": {
			"type": "string"
		},
		"model": { "type": "string" },
		"schema": { "type": "string" },
		"allowAddress": { "type": "string" },
		"allowOrigin": { "type,": "string" },
		"actions": {
			"type": "object",
			"patternProperties": {
				".+": {
					"type": "object",
					"properties": {
						"index": { "type": "boolean" },
						"source": { "type": "string" },
						"schema": { "type": "string" },
						"model": { "type": "string" },
						"view": { "type": "string" },
						"viewMobile": { "type": "string" },
						"template": { "type": "string" },
						"merge": {
							"type": "object",
							"properties": {
								"source": { "type": "string" },
								"model": { "type": "string" },
								"schema": { "type": "string" }
							},
							"additionalProperties": false
						},
						"events": {
							"type": "object",
							"properties": {
								"afterSave": {
									"type": "object",
									"properties": {
										"source": { "type": "string" },
										"schema": { "type": "string" },
										"model": { "type": "string" }
									}
								}
							}
						},
						"export": {
							"type": "object",
							"properties": {
								"template": { "type": "string" },
								"fileName": { "type": "string" },
								"format": {
									"type": "string",
									"enum": [ "xlsx" ]
								}
							},
							"additionalProperties": false
						},
						"parameters": { "type": "object" }
					},
					"additionalProperties": false
				}
			}
		},
		"dialogs": {
			"type": "object",
			"patternProperties": {
				".+": {
					"type": "object",
					"properties": {
						"index": { "type": "boolean" },
						"source": { "type": "string" },
						"schema": { "type": "string" },
						"model": { "type": "string" },
						"view": { "type": "string" },
						"template": { "type": "string" },
						"copy": { "type": "boolean" },
						"hook": {
							"type": "string",
							"pattern": "^\\s*clr-type\\s*:\\s*([\\w\\.]+)\\s*;\\s*assembly\\s*=\\s*([\\w\\.]+)\\s*$"
						},
						"merge": {
							"type": "object",
							"properties": {
								"source": {
									"type": "string"
								},
								"model": {
									"type": "string"
								},
								"schema": {
									"type": "string"
								}
							},
							"additionalProperties": false
						},
						"twoPhase": { "type": "boolean" },
						"parameters": { "type": "object" }
					},
					"additionalProperties": false
				}
			}
		},
		"popups": {
			"type": "object",
			"patternProperties": {
				".+": {
					"type": "object",
					"properties": {
						"schema": { "type": "string" },
						"source": { "type": "string" },
						"model": { "type": "string" },
						"view": { "type": "string" },
						"template": { "type": "string" }
					},
					"additionalProperties": false
				}
			}
		},
		"commands": {
			"type": "object",
			"patternProperties": {
				".+": {
					"type": "object",
					"properties": {
						"type": {
							"type": "string",
							"enum": [ "sql", "clr", "script", "xml", "startProcess", "resumeProcess", "callApi", "file", "sendMessage", "javascript" ]
						},
						"schema": { "type": "string" },
						"source": { "type": "string" },
						"model": { "type": "string" },
						"command": { "type": "string" },
						"procedure": { "type": "string" },
						"clrType": {
							"type": "string",
							"pattern": "^\\s*clr-type\\s*:\\s*([\\w\\.]+)\\s*;\\s*assembly\\s*=\\s*([\\w\\.]+)\\s*$"
						},
						"invoke": {
							"type": "string",
							"pattern": "^\\s*clr-type\\s*:\\s*([\\w\\.]+)\\s*;\\s*assembly\\s*=\\s*([\\w\\.]+)\\s*$"
						},
						"async": { "type": "boolean" },
						"method": {
							"type": "string",
							"enum": [ "get", "post", "put", "delete" ]
						},
						"authorize": { "type": "boolean" },
						"allowOrigin": { "type": "string" },
						"errorCode": { "type": "number" },
						"parameters": { "type": "object" },
						"file": { "type": "string" }
					},
					"additionalProperties": false
				}
			}
		},
		"reports": {
			"type": "object",
			"patternProperties": {
				".+": {
					"type": "object",
					"properties": {
						"schema": { "type": "string" },
						"source": { "type": "string" },
						"name": { "type": "string" },
						"report": { "type": "string" },
						"type": {
							"type": "string",
							"enum": [ "stimulsoft" ]
						}
					},
					"additionalProperties": false
				}
			}
		},
		"files": {
			"type": "object",
			"patternProperties": {
				".+": {
					"type": "object",
					"properties": {
						"model": { "type": "string" },
						"type": {
							"type": "string",
							"enum": [ "parse", "clr" ]
						},
						"parse": {
							"type": "string",
							"enum": [ "excel", "xlsx", "csv", "dbf", "xml", "auto" ]
						},
						"async": { "type": "boolean" },
						"clrType": {
							"type": "string",
							"pattern": "^\\s*clr-type\\s*:\\s*([\\w\\.]+)\\s*;\\s*assembly\\s*=\\s*([\\w\\.]+)\\s*$"
						},
						"availableModels": {
							"type": "array",
							"items": {
								"type": "object",
								"properties": {
									"name": { "type": "string" },
									"columns": { "type": "string" },
									"source": { "type": "string" },
									"schema": { "type": "string" },
									"model": { "type": "string" },
									"parameters": {"type": "object"}
								},
								"additionalProperties": false
							}
						}
					},
					"additionalProperties": false
				}
			}
		}

	},
	"additionalProperties": false
}

=== alex-kukhtin/A2v10.App.Designer/A2v10.Application/App_application/sample/document/waybill/model.json
{
  "schema": "sample",
  "model": "Document",
  "actions": {
    "index": {
      "template": "index.template",
      "view": "index.view",
      "index": true,
      "parameters": {
        "Kind": "WBIN"
      }
    }
  },
  "dialogs": {
    "edit": {
      "template": "../document/edit.template",
      "view": "../document/edit.dialog",
      "parameters": {
        "Kind": "WBIN"
      }
    }
  }
}

=== alex-kukhtin/A2v10.App.Designer/Application/catalog/customer/model.json
{
  "schema": "sample",
  "model": "Customer",
  "actions": {
    "index": {
      "template": "index.template",
      "view": "index.view",
      "index": true
    }
  },
  "dialogs": {
    "edit": {
      "template": "edit.template",
      "view": "edit.dialog"
    },
    "browse": {
      "view": "browse.dialog",
      "index": true
    }
  },
  "commands": {
    "fetch": {
      "type": "sql",
      "procedure": "Customer.Fetch"
    }
  }
}

=== alex-kukhtin/A2v10.App.Designer/A2v10.Application/App_application/sample/document/document/model.json
{
  "schema": "sample",
  "model": "Document",
  "actions": {
    "index": {
      "template": "index.template",
      "view": "index.view",
      "index": true
    },
    "edit": {
      "template": "edit.template",
      "view": "edit.view"
    }
  },
  "dialogs": {
    "edit": {
      "template": "edit.template",
      "view": "edit.dialog"
    }
  }
}

=== alex-kukhtin/A2v10.App.Designer/A2v10.Application/App_application/sample/catalog/agent/model.json
{
  "schema": "sample",
  "model": "Agent",
  "actions": {
    "index": {
      "template": "index.template",
      "view": "index.view",
      "index": true
    }
  },
  "dialogs": {
    "edit": {
      "template": "edit.template",
      "view": "edit.dialog"
    },
    "browse": {
      "view": "browse.dialog",
      "index": true
    }
  },
  "commands": {
    "fetch": {
      "type": "sql",
      "procedure": "Agent.Fetch"
    }
  }
}

=== alex-kukhtin/A2v10.App.Designer/A2v10.Application/App_application/sample/catalog/customer/model.json
{
  "schema": "sample",
  "model": "Agent",
  "actions": {
    "index": {
      "template": "../agent/index.template",
      "view": "../agent/index.view",
      "index": true,
      "parameters": {
        "Kind": "CUST"
      }
    }
  },
  "dialogs": {
    "edit": {
      "template": "../agent/edit.template",
      "view": "../agent/edit.dialog",
      "parameters": {
        "Kind": "CUST"
      }
    },
    "browse": {
      "view": "../agent/browse.dialog",
      "index": true,
      "parameters": {
        "Kind": "CUST"
      }
    }
  },
  "commands": {
    "fetch": {
      "type": "sql",
      "procedure": "Agent.Fetch",
      "parameters": {
        "Kind": "CUST"
      }
    }
  }
}
